version: '3.7'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: crowd_source_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: crowd_source_app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - crowd_source_app_network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: crowd_source_app_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8112:80"
            - "445:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - crowd_source_app_network

    #MySQL Service
    db:
        image: mysql:8.0
        container_name: crowd_source_mysql_server
        restart: unless-stopped
        tty: true
        ports:
            - "3316:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/mysql/mysql-files:/var/lib/mysql-files
        networks:
            - crowd_source_app_network

#Docker Networks
networks:
    crowd_source_app_network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
# docker-compose down -v && docker-compose up -d
